// src/components/help/strings.ts
import { HELP_LANGUAGES, type HelpLanguage } from '@haiwave/protocol';

/** Fallback when haiCore's budget error carries no `details.contact` (master-plan CONTRACT NOTE 1). */
export const DEFAULT_SUPPORT_CONTACT = 'support@haiwave.ai';

export const HELP_STRING_KEYS = [
  'title',
  'openHelp',
  'newAnswer',
  'language',
  'reset',
  'minimize',
  'close',
  'intro',
  'placeholder',
  'messageLabel',
  'send',
  'stop',
  'charCount',
  'masked',
  'thinking',
  'helpful',
  'notHelpful',
  'feedbackNote',
  'feedbackSend',
  'feedbackThanks',
  'copy',
  'copied',
  'summarize',
  'summaryIntro',
  'summaryFailed',
  'footerEdition',
  'mismatch',
  'budget',
  'contact',
  'rateLimited',
  'unavailable',
  'withheld',
  'error',
  'interrupted',
  'retry',
  'sessionExpired',
] as const;

export type HelpStringKey = (typeof HELP_STRING_KEYS)[number];

export const HELP_LANGUAGE_LABELS: Record<HelpLanguage, string> = {
  en: 'English',
  es: 'Español',
  ko: '한국어',
  'pt-BR': 'Português (Brasil)',
};

export const HELP_STRINGS: Record<HelpLanguage, Record<HelpStringKey, string>> = {
  en: {
    title: 'HAIWAVE Help',
    openHelp: 'Help',
    newAnswer: 'new answer',
    language: 'Language',
    reset: 'Start a new conversation',
    minimize: 'Minimize',
    close: 'Close and clear this conversation',
    intro: 'Ask where to find something in the console, what a term means, or how to get your agent deployed and running.',
    placeholder: 'Ask a question or paste an error…',
    messageLabel: 'Message',
    send: 'Send',
    stop: 'Stop',
    charCount: '{count} / {max}',
    masked: 'Secrets masked before sending: {count}',
    thinking: 'Thinking…',
    helpful: 'Helpful',
    notHelpful: 'Not helpful',
    feedbackNote: 'What was wrong? (optional)',
    feedbackSend: 'Send feedback',
    feedbackThanks: 'Thanks for the feedback.',
    copy: 'Copy',
    copied: 'Copied',
    summarize: 'Summarize for support',
    summaryIntro: 'Copy this summary and send it to {contact}.',
    summaryFailed: "Couldn't create the summary — try again.",
    footerEdition: 'Guide {edition} · help pack {date}',
    mismatch: 'Help may be ahead of or behind the guide you downloaded.',
    budget: 'Daily help limit reached; resets 00:00 UTC.',
    contact: 'Contact {contact}',
    rateLimited: 'One moment…',
    unavailable: 'Help is temporarily unavailable.',
    withheld: "I can't help with that one.",
    error: 'Something went wrong — try again.',
    interrupted: 'Interrupted — ask again.',
    retry: 'Retry',
    sessionExpired: 'Your session ended — reload the page to sign in.',
  },
  es: {
    title: 'Ayuda de HAIWAVE',
    openHelp: 'Ayuda',
    newAnswer: 'respuesta nueva',
    language: 'Idioma',
    reset: 'Iniciar una conversación nueva',
    minimize: 'Minimizar',
    close: 'Cerrar y borrar esta conversación',
    intro: 'Pregunte dónde encontrar algo en la consola, qué significa un término o cómo implementar y poner en marcha su agente.',
    placeholder: 'Haga una pregunta o pegue un error…',
    messageLabel: 'Mensaje',
    send: 'Enviar',
    stop: 'Detener',
    charCount: '{count} / {max}',
    masked: 'Secretos ocultados antes de enviar: {count}',
    thinking: 'Pensando…',
    helpful: 'Útil',
    notHelpful: 'No fue útil',
    feedbackNote: '¿Qué estuvo mal? (opcional)',
    feedbackSend: 'Enviar comentarios',
    feedbackThanks: 'Gracias por sus comentarios.',
    copy: 'Copiar',
    copied: 'Copiado',
    summarize: 'Resumir para soporte',
    summaryIntro: 'Copie este resumen y envíelo a {contact}.',
    summaryFailed: 'No se pudo crear el resumen; inténtelo de nuevo.',
    footerEdition: 'Guía {edition} · paquete de ayuda {date}',
    mismatch: 'La ayuda puede estar más adelantada o más atrasada que la guía que descargó.',
    budget: 'Se alcanzó el límite diario de ayuda; se restablece a las 00:00 UTC.',
    contact: 'Escriba a {contact}',
    rateLimited: 'Un momento…',
    unavailable: 'La ayuda no está disponible temporalmente.',
    withheld: 'No puedo ayudarle con eso.',
    error: 'Algo salió mal; inténtelo de nuevo.',
    interrupted: 'Interrumpido; vuelva a preguntar.',
    retry: 'Reintentar',
    sessionExpired: 'Su sesión terminó; recargue la página para iniciar sesión.',
  },
  ko: {
    title: 'HAIWAVE 도움말',
    openHelp: '도움말',
    newAnswer: '새 답변',
    language: '언어',
    reset: '새 대화 시작',
    minimize: '최소화',
    close: '닫고 이 대화 지우기',
    intro: '콘솔에서 무언가를 찾을 위치, 용어의 의미, 또는 에이전트를 배포하고 실행하는 방법을 물어보세요.',
    placeholder: '질문을 입력하거나 오류를 붙여 넣으세요…',
    messageLabel: '메시지',
    send: '보내기',
    stop: '중지',
    charCount: '{count} / {max}',
    masked: '전송 전에 가려진 비밀 값: {count}개',
    thinking: '생각 중…',
    helpful: '도움이 됨',
    notHelpful: '도움이 되지 않음',
    feedbackNote: '무엇이 잘못되었나요? (선택 사항)',
    feedbackSend: '피드백 보내기',
    feedbackThanks: '피드백을 보내 주셔서 감사합니다.',
    copy: '복사',
    copied: '복사됨',
    summarize: '지원팀용 요약',
    summaryIntro: '이 요약을 복사하여 {contact}(으)로 보내세요.',
    summaryFailed: '요약을 만들지 못했습니다. 다시 시도하세요.',
    footerEdition: '가이드 {edition} · 도움말 팩 {date}',
    mismatch: '도움말이 다운로드한 가이드보다 최신이거나 이전 버전일 수 있습니다.',
    budget: '일일 도움말 한도에 도달했습니다. 00:00 UTC에 초기화됩니다.',
    contact: '{contact}(으)로 문의하세요',
    rateLimited: '잠시만 기다려 주세요…',
    unavailable: '도움말을 일시적으로 사용할 수 없습니다.',
    withheld: '그 질문은 도와드릴 수 없습니다.',
    error: '문제가 발생했습니다. 다시 시도하세요.',
    interrupted: '중단되었습니다. 다시 질문하세요.',
    retry: '다시 시도',
    sessionExpired: '세션이 종료되었습니다. 페이지를 새로 고쳐 로그인하세요.',
  },
  'pt-BR': {
    title: 'Ajuda HAIWAVE',
    openHelp: 'Ajuda',
    newAnswer: 'nova resposta',
    language: 'Idioma',
    reset: 'Iniciar uma nova conversa',
    minimize: 'Minimizar',
    close: 'Fechar e apagar esta conversa',
    intro: 'Pergunte onde encontrar algo no console, o que significa um termo ou como implantar e executar seu agente.',
    placeholder: 'Faça uma pergunta ou cole um erro…',
    messageLabel: 'Mensagem',
    send: 'Enviar',
    stop: 'Parar',
    charCount: '{count} / {max}',
    masked: 'Segredos mascarados antes do envio: {count}',
    thinking: 'Pensando…',
    helpful: 'Útil',
    notHelpful: 'Não foi útil',
    feedbackNote: 'O que estava errado? (opcional)',
    feedbackSend: 'Enviar feedback',
    feedbackThanks: 'Obrigado pelo feedback.',
    copy: 'Copiar',
    copied: 'Copiado',
    summarize: 'Resumir para o suporte',
    summaryIntro: 'Copie este resumo e envie para {contact}.',
    summaryFailed: 'Não foi possível criar o resumo — tente novamente.',
    footerEdition: 'Guia {edition} · pacote de ajuda {date}',
    mismatch: 'A ajuda pode estar mais adiantada ou mais atrasada que o guia que você baixou.',
    budget: 'Limite diário de ajuda atingido; reinicia às 00:00 UTC.',
    contact: 'Fale com {contact}',
    rateLimited: 'Um momento…',
    unavailable: 'A ajuda está temporariamente indisponível.',
    withheld: 'Não posso ajudar com isso.',
    error: 'Algo deu errado — tente novamente.',
    interrupted: 'Interrompido — pergunte novamente.',
    retry: 'Tentar novamente',
    sessionExpired: 'Sua sessão terminou — recarregue a página para entrar.',
  },
};

export function t(lang: HelpLanguage, key: HelpStringKey, vars: Record<string, string | number> = {}): string {
  return HELP_STRINGS[lang][key].replace(/\{(\w+)\}/g, (whole, name: string) =>
    Object.prototype.hasOwnProperty.call(vars, name) ? String(vars[name]) : whole,
  );
}

/** First of the browser's preferred languages that maps onto one of the four; English otherwise (spec §7.3). */
export function resolveDefaultLanguage(preferred: readonly string[]): HelpLanguage {
  for (const raw of preferred) {
    // The language subtag, not the first two letters: 'kok-IN' is Konkani, not Korean.
    const language = raw.toLowerCase().split(/[-_]/)[0];
    if (language === 'pt') return 'pt-BR';
    if (language === 'es') return 'es';
    if (language === 'ko') return 'ko';
    if (language === 'en') return 'en';
  }
  return 'en';
}

export function isHelpLanguage(v: unknown): v is HelpLanguage {
  return typeof v === 'string' && (HELP_LANGUAGES as readonly string[]).includes(v);
}
